/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author beca1
 */
public class FormI1 extends javax.swing.JFrame {

    /**
     * Creates new form FormI1
     */
    public FormI1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fant = new javax.swing.JLabel();
        rome = new javax.swing.JLabel();
        lg = new javax.swing.JLabel();
        suspen1 = new javax.swing.JLabel();
        terr = new javax.swing.JLabel();
        aventu = new javax.swing.JLabel();
        cla = new javax.swing.JLabel();
        poe = new javax.swing.JLabel();
        mnprincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        fant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fantMouseClicked(evt);
            }
        });
        getContentPane().add(fant);
        fant.setBounds(80, 220, 170, 40);

        rome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                romeMouseClicked(evt);
            }
        });
        getContentPane().add(rome);
        rome.setBounds(80, 140, 170, 30);

        lg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgMouseClicked(evt);
            }
        });
        getContentPane().add(lg);
        lg.setBounds(80, 310, 180, 30);

        suspen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suspen1MouseClicked(evt);
            }
        });
        getContentPane().add(suspen1);
        suspen1.setBounds(340, 140, 180, 40);

        terr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terrMouseClicked(evt);
            }
        });
        getContentPane().add(terr);
        terr.setBounds(340, 220, 180, 40);

        aventu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aventuMouseClicked(evt);
            }
        });
        getContentPane().add(aventu);
        aventu.setBounds(340, 310, 180, 40);

        cla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                claMouseClicked(evt);
            }
        });
        getContentPane().add(cla);
        cla.setBounds(590, 180, 180, 40);

        poe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poeMouseClicked(evt);
            }
        });
        getContentPane().add(poe);
        poe.setBounds(590, 270, 180, 40);

        mnprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Email (3).png"))); // NOI18N
        getContentPane().add(mnprincipal);
        mnprincipal.setBounds(0, 0, 850, 440);

        setSize(new java.awt.Dimension(863, 464));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fantMouseClicked

        new FormFan().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_fantMouseClicked

    private void romeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_romeMouseClicked

        new FormRoma().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_romeMouseClicked

    private void lgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseClicked

        new FormL().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lgMouseClicked

    private void terrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terrMouseClicked

        new FormTer().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_terrMouseClicked

    private void suspen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suspen1MouseClicked
          new FormSus().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_suspen1MouseClicked

    private void poeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poeMouseClicked
        new FormPoe().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_poeMouseClicked

    private void aventuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aventuMouseClicked
         new FormAve().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_aventuMouseClicked

    private void claMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claMouseClicked
        new FormClas().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_claMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormI1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aventu;
    private javax.swing.JLabel cla;
    private javax.swing.JLabel fant;
    private javax.swing.JLabel lg;
    private javax.swing.JLabel mnprincipal;
    private javax.swing.JLabel poe;
    private javax.swing.JLabel rome;
    private javax.swing.JLabel suspen1;
    private javax.swing.JLabel terr;
    // End of variables declaration//GEN-END:variables
}
